### ISSUE TITLE
Dockerfile CI

### ISSUE THREAD

**Issue by alexei-led** [gaia-adm/security-token-service#1]
Dockerfile must contain everything required to:
- build: JDK, MVN inside
- test: both unit and system level
- run: configure run parameters with `CMD`
  service

**Comment by boriska70** [comment]
I thought about different approach - let's say we have a CI that builds the project, run tests, and run docker build command only in case all previous steps succeeded. In this case the image will be small and working. And we separate responsibilities - CI build and verify, docker - deploy. And the process will be faster, probably.

**Comment by jaroslavl1** [comment]
My opinion is Docker should be used just to build the image of complete app.

To build the app, you would use maven, grunt etc. You get Java WAR + Jetty. Maven can also run unit tests and if all succeeds build the Docker image. CI runs the Docker image and we somehow run system tests in it.

I'm not sure how to run system tests in Docker, as we probably want 1 Docker app production image and be able to run tests on that. Or just deploy already tested image. A production image would start Jetty/Node.js immediately therefore not allowing much apart from REST tests. You would actually have to connect to the running docker container, stop Jetty/Node.js and execute system tests. We need to solve this so its not so complicated.

**Comment by alexei-led** [comment]
Jarda, the difference comes from "how do you see the place for Docker in a build process"
I see it as a replacement for **make** file or Maven, if you like. You see it as a replacement for application packaging: war, rpm, etc.
Docker can replace package managers, indeed. But, let's try to take it further and make Dev environment also portable: be able to build and test code on any machine, without any tools/env setup.

**Comment by boriska70** [comment]
The solution is to use 2 dockerfiles - one for building project and another for runtime image.
